apiVersion: v1
kind: Service
metadata:
  name: webook-mysql
spec:
  type: LoadBalancer
  selector:
    app: webook-mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
